### ISSUE TITLE
@coke11 you removed our new features!!!!

### ISSUE THREAD

**Issue by CosmicWebServices** [dragon-drop-scratch/prototype#2]

**Comment by coke11** [comment]
@CosmicWebServices What did I remove?

**Comment by CosmicWebServices** [comment]
A preview button and bug fixes

**Comment by coke11** [comment]
Wait, when was that there?

**Comment by coke11** [comment]
@CosmicWebServices Those buttons never worked in the first place

**Comment by CosmicWebServices** [comment]
They did https://github.com/dragon-drop-scratch/prototype/commit/ff18483245360bf1efecb24990495e1eed4ab6ed

**Comment by coke11** [comment]
@CosmicWebServices Restored in https://dragon-drop-scratch.github.io/prototype/fix.html. If you need it to be in index, you can move it there :)

**Comment by CosmicWebServices** [comment]
OK?
