### ISSUE TITLE
Prototype's background button does not transfer to preveiw

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/prototype#3]
Moved from

dragon-drop-scratch/dragon-drop-www/issues/73

**Comment by card100** [comment]
Ok

**Comment by GreenBayRules** [comment]
I think we got rid of this feature @NaturalmotionStudios @card100

**Comment by coke11** [comment]
@GreenBayRules What feature?

**Comment by NaturalmotionStudios** [comment]
@GreenBayRules ?

**Comment by GreenBayRules** [comment]
@coke11 @NaturalmotionStudios The background color thing.

**Comment by NaturalmotionStudios** [comment]
@GreenBayRules We didn't

**Comment by GreenBayRules** [comment]
@NaturalmotionStudios Yes we did. There is no section with that D:

**Comment by NaturalmotionStudios** [comment]
@GreenBayRules Last time I checked it was under 'Style'. 
![capture](https://cloud.githubusercontent.com/assets/19719195/19370064/4dd1dc36-9177-11e6-9d28-fe835563f19e.PNG)

**Comment by GreenBayRules** [comment]
Yeah, it is. My bad my computer was szoomed in
