### ISSUE TITLE
Youtube embeds don't work sometimes

### ISSUE THREAD

**Issue by NaturalmotionStudios** [dragon-drop-scratch/prototype#4]
So, I was on my school tablet, and I went to the DragonDrop editor. I tried to embed a YT video and it kept saying <b><i>The connection was reset</b></i>

**Comment by coke11** [comment]
@NaturalmotionStudios Staging?

**Comment by NaturalmotionStudios** [comment]
@coke11 ?

**Comment by csf30816** [comment]
It is because of HTTPS

**Comment by csf30816** [comment]
Cannot load HTTP on an HTTPS server

**Comment by NaturalmotionStudios** [comment]
But it doesn't say that it's not secure

**Comment by GreenBayRules** [comment]
Fixed.

**Comment by NaturalmotionStudios** [comment]
@GreenBayRules Thanks
