### ISSUE TITLE
Scratcher and Non Scratcher Section

### ISSUE THREAD

**Issue by coke11** [dragon-drop-scratch/prototype#5]
Originally the plan was to have features like Scratch embed in a Scratcher section that only people who signed up as a Scratch user could see, and features like email and E-commerce in a section that only non-Scratchers could see. But we sort of skipped right past that. Could we work on adding this?

**Comment by coke11** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Newsletter Sign Up Features](https://trello.com/c/rIo9rSAC/207-newsletter-sign-up-features)

**Comment by GreenBayRules** [comment]
Anyone doing this

**Comment by coke11** [comment]
@GreenBayRules Nope. You can go ahead and do it if you want.

**Comment by GreenBayRules** [comment]
I think this should be on trello, not github
