### ISSUE TITLE
Totally UnSecure

### ISSUE THREAD

**Issue by GreenBayRules** [dragon-drop-scratch/prototype#9]
You can easily find the password, by typing "password" in the console. We need to use a database (I think) to avoid these problems.

**Comment by coke11** [comment]
@GreenBayRules Come to think about it, this really isn't that bad - really this is an alpha anyone can sign up for, not a super secret password or anything. Maybe, though, we could edit the "password" variable so you need to type something else into the console.

**Comment by GreenBayRules** [comment]
I did

Sent from my iPhone

On Oct 16, 2016, at 11:32 AM, coke11 <notifications@github.com<mailto:notifications@github.com>> wrote:


@GreenBayRules<https://github.com/GreenBayRules> Come to think about it, this really isn't that bad - really this is an alpha anyone can sign up for, not a super secret password or anything. Maybe, though, we could edit the "password" variable so you need to type something else into the console.

-

**Comment by coke11** [comment]
k

**Comment by csf30816** [comment]
We do not need a DB we need (if it is to be secured) PHP So that nobody no matter how hard they look can find the password var... Or We need an .htaccess file

**Comment by adri326** [comment]
Yeah, gh-pages are limited, I vote for PHP

**Comment by liam4** [comment]
Don't forget to hash the password so even if somebody did find the password, they still wouldn't be able to log in with it (since they'd have the hash, not the password)!

**Comment by zebraislearning** [comment]
I think it should be seqaure

**Comment by CosmicWebServices** [comment]
I mean it is just a prototype... do you really need a password system?

**Comment by liam4** [comment]
If the site has no backend you don't need a password system. So if you're just prototyping the editor, but not any hosting setup, you might not need a password system. (That is, assuming the editor doesn't need any access to new user accounts, since those need passwords.)

**Comment by coke11** [comment]
Just to clarify, the password serves two purposes and is not in as a measure of security. The first reason is so that people who do not know what they are doing do not get in the editor and get bad first impressions about our editor. Frankly, if you are able to get the password I think you can figure out how to use it without any instruction. The other reason why we added the password as just to test out passwords, but most importantly the animation and color scheme.

Thank you, everybody, for your continued support,
Coke11
Executive
DragonDrop

**Comment by coke11** [comment]
I am going to go ahead and close this issue just because a 100% secure password to get on the PROTOTYPE editor is not a requirement atm.
